Better classification results
orobix/quadra pull request #56
Opened 2023-09-13 10:07 UTC by AlessandroPolidori

## Summary

Describe the purpose of the pull request, including:

- What problem does it solve?
- How does it solve the problem?
- What are the benefits of the solution?
- Any relevant background or context information.
- Reference any relevant issues or pull requests.

## Type of Change

Please select the one relevant option below:

- Bug fix (non-breaking change that solves an issue)
- New feature (non-breaking change that adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation update
- Other (please describe):

## Checklist

Please confirm that the following tasks have been completed:

- [ ] I have tested my changes locally and they work as expected. (Please describe the tests you performed.)
- [ ] I have added unit tests for my changes, or updated existing tests if necessary.
- [ ] I have updated the documentation, if applicable.
- [ ] I have installed pre-commit and run locally for my code changes.

## Screenshots or Visuals (Optional)

If applicable, please provide screenshots, diagrams, graphs, or videos of the changes, features or the error.

## Additional Information (Optional)

Please provide any additional information that may be useful for the reviewer, such as:

- Any potential risks or challenges associated with the changes.
- Any instructions for testing or running the code.
- Any other relevant information.

Thank you for your contribution! Once you have filled out this template, please ensure that you have assigned the appropriate reviewers and that all tests have passed.

2023-09-13 15:52 UTC, rcmalli approved these changes

2023-09-13 19:36 UTC, lorenzomammana requested changes
Double check this

2023-09-13 19:36 UTC, lorenzomammana commented on quadra/tasks/classification.py
> +            results=self.res,
Do we really need self.res here? 

Isn't this
self.metadata["test_results"] = self.res

Exactly the same? I would avoid self.res if it's not really needed

2023-09-14 07:15 UTC, lorenzomammana approved these changes
LGTM

2023-09-18 09:57 UTC, merged